### ISSUE TITLE
Is there any way to close the date picker ?

### ISSUE THREAD

**Issue by asotog** [DenTelezhkin/DTPickerPresenter#3]
Hi,
Meant like a close button ,

Thanks in advance

**Comment by DenTelezhkin** [comment]
You can implement one yourself, if you need it. But it's application logic, and not framework decision to make. You may want to add inputAccessoryView with a hide button, or you may want to dismiss picker interactively. There are a lot of ways to react to user input. 

Usually in my applications i use UIScrollView keyboardDismissMode property to hide keyboard.

**Comment by asotog** [comment]
i see, thanks for suggestion
